# Generated by Django 4.0.5 on 2022-11-04 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_alter_artiste_first_name_alter_artiste_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='song_id',
            new_name='song',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artiste_id',
            new_name='artiste',
        ),
        migrations.AddField(
            model_name='lyric',
            name='source',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='date_released',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='song',
            name='likes',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
