# Generated by Django 4.0.5 on 2022-11-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_rename_song_id_lyric_song_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='song',
            new_name='Song',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artiste',
            new_name='Artiste',
        ),
        migrations.RemoveField(
            model_name='artiste',
            name='age',
        ),
        migrations.RemoveField(
            model_name='lyric',
            name='source',
        ),
        migrations.AddField(
            model_name='artiste',
            name='Age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lyric',
            name='song_id',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='song',
            name='artiste_id',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='content',
            field=models.TextField(max_length=3500, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='likes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
